### ISSUE TITLE
Web container is in exited status in several seconds after starting

### ISSUE THREAD

**Issue by ermolnik** [fractalliter/ktor-postgres-backend#7]
Hi, I'm new in docker, I have found your repo and try to create docker compose config like your. When I try to launch your app, web container are stopped in several seconds with logs something like this  "BUILD SUCCESSFUL in 4s
2023-08-23T20:21:56.669102797Z 6 actionable tasks: 6 up-to-date" 

In my app with your docker compose file  I have another problem "Exception in thread "main" org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused."

My repo is available on following link https://github.com/ermolnik/mylife_be 
Could you help me to launch pgsql with ktor in docker container?

**Comment by fractalliter** [comment]
Hi Sergei,

I see in your example that you would like to make a network connection between ktor server container and PostgreSQL database container but instead you make a connection to a localhost port in ktor server container. In your case name of the database service in docker compose config is `testdb`. If you replace `127.0.0.1` with testdb for jdbc url in your `application.yaml` file. then docker compose will resolve it with the ip of PostgreSQL database container and you'd be fine.
